### ISSUE TITLE
Support of SiliFuzz in Intel Skylake (Client) CPUs

### ISSUE THREAD

**Issue by ElaineYao** [google/silifuzz#7]
Hi,

I used the command below to check SiliFuzz's support for my CPU:
`PLATFORM_ID=$(./tools/silifuzz_platform_id)` 
The output indicates that my Intel Skylake (Client) CPU is unsupported:
```
E0000 00:00:1696353932.029503  366275 [platform.cc:103](https://github.com/google/silifuzz/blob/346fe5f5eed2427142baa2ef405385f06d3ac89e/util/x86_64/platform.cc#L95)] Unknown Intel platform: family = 6 model = 94 stepping = 3
Unsupported platform
```

After checking the [source code](https://github.com/google/silifuzz/blob/346fe5f5eed2427142baa2ef405385f06d3ac89e/util/x86_64/platform.cc#L95) and the [Wiki](https://en.wikichip.org/wiki/intel/cpuid#Family_6), I found that SiliFuzz supports Intel Skylake (Server) CPUs with model 85.

I wonder if it's possible for SiliFuzz to support Intel Skylake (Client) CPUs with model 94 as well?

**Comment by ksteuck** [comment]
Hi @ElaineYao,

Client versions of Skylake are not the same as the server in terms of ISA level support so we cannot simply change the code you linked to to read `if (model == 85 || model = 94)`.  However, you can make this change in your local repo and the rest of the code will just work. You will need to keep in mind that "Skylake" in your case means Skylake Client and not try to run the same corpus on Skylake Server.
We will not be supporting model 94 in the upstream because we don't have access to such machines.
